name: main
on:
  push:
    branches:
      - main
jobs:
  check_runner_status:
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: test
        run: echo "test"
      - name: echo
        run: |
          echo "--id $(git log -n 1 --pretty=format:%h) --message $(git log -n 1 --pretty=format:%s) --result ${{ steps.test.outcome }}"

